Stat svc
DmitriiDerendyaev/exploreWithMe pull request #1
Opened 2024-04-23 21:26 UTC by DmitriiDerendyaev

2024-04-24 06:18 UTC, VadimZharkov commented on docker-compose.yml
> +    # Вадим, подскажи, пожалуйста: если я через билд просто указываю на расположение докерфайла и имя контейнера он падает, если указать полностью имя образа(который я заранее собрал), то композ рабо
Не совсем понял последовательность действий.
Чтобы собрать сервисы и поместить их в контейнеры делаем docker compose build
И соответственно для каждого сервиса должен быть указан dockerfile как инструкция как собрать образ для контейнера.
Чтобы запустить контейнеры делаем docker compose up
Докер начнет собирать, если не найдет у себя уже раннее собранных или выкаченных из dockerhub образов.

2024-04-24 06:22 UTC, VadimZharkov commented on pom.xml
> +	<dependencies>
зависимости нужно поместить в каждый дочерний pom, т.к. у каждого модуля может быть свой набор зависимостей. А из родительского может подтянуться масса неужных зависимостей

2024-04-24 06:23 UTC, VadimZharkov commented on stats/pom.xml
> +    <properties>
свойства лучше поместить в самый верхний родительский. версия джавы и кодировка будут у всех модулей одинаковые

2024-04-24 06:25 UTC, VadimZharkov commented on stats/stats-server/src/main/java/org/example/exception/ErrorHandler.java
> +}
Не забываем Throwable в INTERNAL_SERVER_ERROR

2024-04-24 06:25 UTC, VadimZharkov commented on stats/stats-server/src/main/java/org/example/exception/ErrorHandler.java
> +    public Map<String, String> handlerStatsValidationException(StatsValidationException e) {
Вместо мапы лучше свой классик ErrorResponse сделать.

2024-04-24 06:26 UTC, VadimZharkov requested changes
Можно улучшить

2024-04-26 05:09 UTC, DmitriiDerendyaev commented on pom.xml
> +	<dependencies>
Попрбовать можно, конечно)

Но кажется, уж очень много потом получается связей и в голове держать - где какие зависимости лежат, чтобы не ошибиться

2024-04-26 05:32 UTC, DmitriiDerendyaev commented on docker-compose.yml
> +    # Вадим, подскажи, пожалуйста: если я через билд просто указываю на расположение докерфайла и имя контейнера он падает, если указать полностью имя образа(который я заранее собрал), то композ рабо
Вот момент с docker compose build я и упустил, принял!

2024-04-26 07:40 UTC, VadimZharkov approved these changes

2024-04-26 18:49 UTC, merged