Main svc
DmitriiDerendyaev/exploreWithMe pull request #2
Opened 2024-05-03 19:01 UTC by DmitriiDerendyaev

2024-05-06 07:46 UTC, VadimZharkov commented on ewm-service/src/main/java/org/example/compilation/controller/CompilationController.java
> +                                                       @RequestParam(required = false, defaultValue = "0") Integer from,
required = false, defaultValue = "0" противоречат друг другу, т.к. какое-то значение у параметра будет всегда

2024-05-06 07:51 UTC, VadimZharkov commented on ewm-service/src/main/java/org/example/compilation/model/Compilation.java
> +    @ManyToMany
можно ленивую загрузку добавить
@ManyToMany(fetch = FetchType.LAZY)
чтобы из базы, только по первому обращению к полю грузилось, а не в момент создания сущности

2024-05-06 07:54 UTC, VadimZharkov commented on ewm-service/src/main/java/org/example/event/dto/NewEventDto.java
> +    @NotNull
` @NotBlank содержит в себе @NotNull` поэтому обе аннотации избыточно указывать

2024-05-06 08:11 UTC, VadimZharkov commented on ewm-service/src/main/java/org/example/exceprtion/ErrorHandler.java
> +}
Не забываем про все оставшиеся эксепшены. Throwable в INTERNAL_SERVER_ERROR

2024-05-06 08:14 UTC, VadimZharkov commented on ewm-service/src/main/java/org/example/exceprtion/ErrorHandler.java
> +package org.example.exceprtion;
exceprtion - синтакс. ошибка

2024-05-06 08:15 UTC, VadimZharkov requested changes
нужно исправить небольшие замечания

2024-05-06 18:14 UTC, DmitriiDerendyaev commented on ewm-service/src/main/java/org/example/compilation/controller/CompilationController.java
> +                                                       @RequestParam(required = false, defaultValue = "0") Integer from,
Мне казалось, что поэтому required и false, потому что есть дефолтное значение

2024-05-08 07:01 UTC, VadimZharkov commented on ewm-service/src/main/java/org/example/compilation/controller/CompilationController.java
> +                                                       @RequestParam(required = false, defaultValue = "0") Integer from,
Я не совсем корректно выразился. Когда установлен required=false то это говорит о том, что параметр опциональный, т.е. ендпоинт должен сработать и когда параметр есть и когда его нет. И если его нет то параметру в методе присваивается null и дальше логика должна это учитывать.
Тоже самое для defaultValue, но параметру метода присваивается не нул, а определенное значение. и нул обрабатывать нет необходимости.
В общем если есть defaultValue, то required = false указывать не обязательно, т.к. оно итак подразумевается но не явно.

2024-05-08 07:02 UTC, VadimZharkov approved these changes

2024-05-09 19:23 UTC, merged

2024-05-09 19:56 UTC, DmitriiDerendyaev commented on ewm-service/src/main/java/org/example/compilation/controller/CompilationController.java
> +                                                       @RequestParam(required = false, defaultValue = "0") Integer from,
Спасибо большое, теперь однозначно понял)